//! [0]

#if defined __cplusplus
#include <QAbstractItemModel>
#include <QAbstractItemView>
#include <QAction>
#include <QApplication>
#include <QBuffer>
#include <QByteArray>
#include <QClipboard>
#include <QColor>
#include <QColorDialog>
#include <QComboBox>
#include <QCompleter>
#include <QDate>
#include <QDebug>
//#include <QDesktopWidget>
#include <QDialog>
#include <QDomComment>
#include <QDrag>
#include <QEventLoop>
#include <QFile>
#include <QFileDialog>
#include <QFileInfo>
#include <QFileSystemWatcher>
#include <QFont>
#include <QFontComboBox>
#include <QFrame>
#include <QGraphicsItem>
#include <QGraphicsScene>
#include <QGraphicsSceneMouseEvent>
#include <QGraphicsTextItem>
#include <QGraphicsView>
#include <QHash>
#include <QIcon>
#include <QImage>
#include <QJSValueIterator>
#include <QKeyEvent>
#include <QLabel>
#include <QList>
#include <QLocale>
#include <QMainWindow>
#include <QMap>
#include <QMenu>
#include <QMessageBox>
#include <QMetaObject>
#include <QMetaType>
#include <QMimeData>
#include <QMouseEvent>
#include <QObject>
#include <QPaintEvent>
#include <QPainter>
#include <QPlainTextEdit>
#include <QPluginLoader>
#include <QPrintDialog>
#include <QPrinter>
#include <QPrinterInfo>
#include <QProgressBar>
#include <QQmlEngine>
#include <QRect>
#include <QRectF>
//#include <QRegExp>
#include <QScopedPointer>
#include <QScreen>
//#include <QScriptValueIterator>
//#include <QScriptable>
#include <QScrollBar>
#include <QSet>
#include <QSettings>
#include <QSharedPointer>
#include <QSortFilterProxyModel>
#include <QSpinBox>
#include <QSqlError>
#include <QSqlQuery>
#include <QSqlQueryModel>
#include <QSqlRecord>
#include <QStandardItemModel>
#include <QString>
#include <QStringList>
#include <QStringListModel>
#include <QStyleOptionGraphicsItem>
#include <QStyleOptionViewItem>
#include <QSyntaxHighlighter>
#include <QTableWidgetItem>
#include <QTextBlock>
#include <QTextDocument>
#include <QTextEdit>
#include <QTextLayout>
#include <QTimer>
#include <QToolBar>
#include <QToolButton>
#include <QUiLoader>
#include <QUuid>
#include <QVBoxLayout>
#include <QVariant>
#include <QVector>
#include <QWidget>
#include <QtGlobal>
#include <QtGui>
#include <QtPlugin>
//#include <QtScript/QScriptEngine>
#include <QtSql/QSqlQuery>
#include <QtSvg>
#include <QtXml>
#endif
//! [0]
